### ISSUE TITLE
How can I use the model (reinf_traf_control.h5) in traffic simulation ? 

### ISSUE THREAD

**Issue by loiloip** [TJ1812/Adaptive-Traffic-Signal-Control-Using-Reinforcement-Learning#2]
How can I import the model (reinf_traf_control.h5) in the simulation in your network simulation ?

**Comment by TJ1812** [comment]
Refer to line 244 in code. The model is saved in the 'Models' folder.

**Comment by loiloip** [comment]
thank you for the quick repond,
But how can I see the simulation of traffic light with this model (reinf_traf_control.h5) ?
Have I comment all lines and just leave this two lines :
try:
        agent.load('Models/reinf_traf_control.h5')
    except:
        print('No models found') ???

**Comment by TJ1812** [comment]
In that case you need to comment out all lines that call any method in Agent class except 'act' method. So you can comment out lines calling remember or replay etc.
