### ISSUE TITLE
Missing lines in the code source ?

### ISSUE THREAD

**Issue by loiloip** [TJ1812/Adaptive-Traffic-Signal-Control-Using-Reinforcement-Learning#3]
for e in range(episodes):
        # DNN Agent
        # Initialize DNN with random weights
        # Initialize target network with same weights as DNN Network
        #log = open('log.txt', 'a')
        step = 0
        waiting_time = 0
 
the three first comments are very important to build the DQN, how could you generate the model (reinf_traf_control.h5 ) without this three ?

**Comment by TJ1812** [comment]
These comments were written before the actual code was written to kind of give idea of how the flow should be like.

If you refer to line 242 in code, the call to DQNA object does all these things.

I agree that the code should have been much more cleaner but I left those few changes to the user.

**Comment by loiloip** [comment]
You're right, In fact you have used the same deep network as a target network. But recent studies shows that the best is to update target network once in 100 epochs for exemple.
Thank you again for your quick response.

**Comment by TJ1812** [comment]
Yes, again this is dependent on the application that you are working on. But feel free to apply different strategies and also feel free to post your results, I would definitely like to see them.
